name: 'test inno package'

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
        
    steps:
      - uses: actions/checkout@v2

      - name: dotnet build
        run: dotnet publish --configuration Release --runtime win-x86 --self-contained False --output publish -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
      
      - name: create inno installer
        run: ISCC.exe ".\install\inno\inno.iss"

      - name: upload artifacts
        shell: bash
        working-directory: install/inno/output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref_name}}
          gh release upload ${{github.ref_name}} ${{ github.event.repository.name }}.Setup.exe
