name: 'test inno package'

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
        
    steps:
      - uses: actions/checkout@v2

      - name: dotnet build
        run: dotnet build -c Release -o publish
        
      - name: create inno installer
        run: ISCC.exe .\install\inno\inno.iss

      - name: upload artifacts
        shell: bash
        working-directory: install/inno/output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref_name}}
          gh release upload ${{github.ref_name}} ${{ github.event.repository.name }}.Setup.exe
