name: 'test inno package'

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
        
    steps:
      - uses: actions/checkout@v2

      - name: test inno
        run: ISCC.exe .\packages\inno\inno.iss
