name: 'test inno package'

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

env:
  VERSION_PROJECT_PATH: '${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj'
  
jobs:
  release:
    runs-on: windows-2022
    permissions:
      contents: write
        
    steps:
      - uses: actions/checkout@v2

      - uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: ${{ env.VERSION_PROJECT_PATH }}
          
      - name: dotnet build
        run: dotnet publish --configuration Release --runtime win-x86 --self-contained False --output publish -p:DebugType=None -p:DebugSymbols=false
        # run: dotnet publish --configuration Release --runtime win-x86 --self-contained False --output publish -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
      
      - name: create inno installer
        run: |
          ISCC.exe ".\install\inno\inno.iss" "/DMyAppVersion=${{ steps.get-version.outputs.assembly-version }}"

      - name: upload artifacts
        shell: bash
        working-directory: install/inno/output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref_name}}
          gh release upload ${{github.ref_name}} ${{ github.event.repository.name }}.Setup.exe
