name: 'test inno package'

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
        
    steps:
      - uses: actions/checkout@v2

      - name: test inno
        run: |
          dir
          pwd
          tree
          dotnet build -c Release -o publish
          ISCC.exe .\install\inno\inno.iss
