name: '[Release] On publish Tag'

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  RID: 'win-x86'
  VERSION_PROJECT_PATH: '${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj'
  
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
        
    steps:
      - uses: actions/checkout@v2

      - uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: ${{ env.VERSION_PROJECT_PATH }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: publish release
        run: dotnet publish --configuration Release --runtime ${{ env.RID }} --self-contained false --output publish/${{ env.RID }} -p:PublishSingleFile=true -p:Version=${{ steps.get-version.outputs.assembly-version }} --verbosity normal
      
      - name: upload artifacts
        shell: bash
        working-directory: publish/${{ env.RID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref_name}}
          gh release upload ${{github.ref_name}} ${{ github.event.repository.name }}.exe